### ISSUE TITLE
Hostname validation fails for longer hostnames

### ISSUE THREAD

**Issue by rupertbenbrook** [tolson-vkn/pifrost#4]
The existing regex to validate hostnames, both for the pihole host and ingress hosts, wouldn't allow longer domains like one.two.three.org.uk. This is valid, so I altered the regex to be more permissive, but still check RFC1123 hostnames.

**Comment by rupertbenbrook** [comment]
Potential fix in PR: https://github.com/tolson-vkn/pifrost/pull/3

**Comment by tolson-vkn** [comment]
Closed in https://github.com/tolson-vkn/pifrost/pull/3 TYSM. :partying_face:
